### ISSUE TITLE
Don't know how to / Can't assign UID when uploading

### ISSUE THREAD

**Issue by mccalluc** [hms-dbmi/higlass-server#13]
Sorry if this something simple I'm missing:
```
set -x
set -v

VIEWCONF='{}'
VIEWCONF_UID=empty-view
VIEWCONFS_URL=http://localhost:8888/api/v1/viewconfs/

# This doesn't work: Trying to curl in two different incompatible ways.
curl --globoff -H "Content-Type: application/json" -X POST -d "$VIEWCONF" $VIEWCONFS_URL -F "uid=$VIEWCONF_UID"

# Not recognized as a parameter in the url: random UID still generated. (GET will work.)
curl --globoff -H "Content-Type: application/json" -X POST -d "$VIEWCONF" $VIEWCONFS_URL'?uid='$VIEWCONF_UID

# UID is not recognized, and the data stored in the database has HTTP cruft. (GET fails because JSON can't be parsed.)
curl --globoff -F "fileupload=$VIEWCONF" -F "uid=$VIEWCONF_UID" $VIEWCONFS_URL

echo
```

**Comment by mccalluc** [comment]
```
curl -u `cat ~/.higlass-server-login` \
     -F 'datafile=@/data/downloads/gene-annotations-hg19.db' \
     -F 'filetype=beddb' \
     -F 'datatype=gene-annotation' \
     -F 'uid=OHJakQICQD6gTD7skx4EWA' \
     -F 'name=Gene Annotations' \
     -F 'coordSystem=hg19' \
     localhost:80/api/v1/tilesets/
```

For comparison, here's tilesets from the google doc. Notice that the examples above are missing credentials, and have a different field for the file. Where does this come from? Are they actually being handled differently?

**Comment by pkerpedjiev** [comment]
Viewconfs don't require credentials and can't be assigned a uuid (at the moment).

Preventing unauthorized file uploads is more important because those are user-visible (e.g. one can click 'add track' and see the list of tracks that are present). Viewconfs are largely invisible. Unless you know the UUID of a particular viewconf, you won't be aware of its existence.

We can make the viewconfs method accept uids. The function `viewconfs` in `tilesets/views.py` is responsible for storing saved viewconfs. 

To see an example of where we store 'uids', take a look at `perform_create` in `tilesets/views.py`.

**Comment by mccalluc** [comment]
I'll take a swing at this. Being able to give the ID when creating a viewconfig would make it a lot easier to describe reproducers.

**Comment by mccalluc** [comment]
This is implemented and tested: https://github.com/hms-dbmi/higlass-server/blob/7e9519d36b1b91d69c5a5e7755bd43cb28a2762f/tilesets/tests.py#L65-L66
